version: "3"
services:
  web:
    build: ./node
    volumes:
      - ./node:/app
    ports:
      - 8080:80
    links:
      - database:db
      - cache:cache
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
  database:
    image: postgres:10.5
    volumes:
      - /var/lib/postgresql/data 
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
  cache:
    image: redis:4.0.11
    volumes:
      - /data


    